export const typeColors = {
	normal: "bg-gray-400",
	fire: "bg-red-500",
	water: "bg-blue-500",
	electric: "bg-yellow-400",
	grass: "bg-green-500",
	ice: "bg-cyan-300",
	fighting: "bg-orange-700",
	poison: "bg-purple-500",
	ground: "bg-yellow-600",
	flying: "bg-indigo-300",
	psychic: "bg-pink-500",
	bug: "bg-lime-500",
	rock: "bg-yellow-800",
	ghost: "bg-indigo-700",
	dragon: "bg-purple-700",
	dark: "bg-gray-800",
	steel: "bg-gray-500",
	fairy: "bg-pink-300"
};

export const typeTranslations = {
	normal: "Normal",
	fire: "Feu",
	water: "Eau",
	grass: "Plante",
	electric: "Électrik",
	ice: "Glace",
	fighting: "Combat",
	poison: "Poison",
	ground: "Sol",
	flying: "Vol",
	psychic: "Psy",
	bug: "Insecte",
	rock: "Roche",
	ghost: "Spectre",
	dragon: "Dragon",
	dark: "Ténèbres",
	steel: "Acier",
	fairy: "Fée"
};